CREATE ROLE "userWithWritesToOhdsiSchema" WITH LOGIN PASSWORD 'PASS';

-- Create OMOP schemas
CREATE SCHEMA IF NOT EXISTS cdm;
CREATE SCHEMA IF NOT EXISTS ohdsi;
CREATE SCHEMA IF NOT EXISTS ohdsi_results;
CREATE SCHEMA IF NOT EXISTS webapi;

-- Grant schema-level permissions
GRANT ALL PRIVILEGES ON SCHEMA ohdsi TO ohdsi_admin;
GRANT ALL PRIVILEGES ON SCHEMA cdm TO ohdsi_admin;
GRANT ALL PRIVILEGES ON SCHEMA ohdsi_results TO ohdsi_admin;
GRANT ALL PRIVILEGES ON SCHEMA ohdsi TO "userWithWritesToOhdsiSchema";
GRANT ALL PRIVILEGES ON SCHEMA cdm TO "userWithWritesToOhdsiSchema";
GRANT ALL PRIVILEGES ON SCHEMA webapi TO ohdsi_admin;

-- Grant permissions on all existing tables (if any)
GRANT ALL PRIVILEGES ON SCHEMA ohdsi TO "userWithWritesToOhdsiSchema";
GRANT ALL PRIVILEGES ON SCHEMA ohdsi_results TO "userWithWritesToOhdsiSchema";
GRANT ALL PRIVILEGES ON SCHEMA webapi TO "userWithWritesToOhdsiSchema";

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA cdm TO ohdsi_admin;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA ohdsi TO ohdsi_admin;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA ohdsi_results TO ohdsi_admin;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA webapi TO ohdsi_admin;

-- Grant permissions on all sequences
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA ohdsi TO "userWithWritesToOhdsiSchema";
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA ohdsi_results TO "userWithWritesToOhdsiSchema";
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA webapi TO "userWithWritesToOhdsiSchema";

GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA cdm TO ohdsi_admin;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA ohdsi TO ohdsi_admin;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA ohdsi_results TO ohdsi_admin;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA webapi TO ohdsi_admin;

-- Set default privileges for future objects
ALTER DEFAULT PRIVILEGES IN SCHEMA ohdsi GRANT ALL ON TABLES TO "userWithWritesToOhdsiSchema";
ALTER DEFAULT PRIVILEGES IN SCHEMA ohdsi_results GRANT ALL ON TABLES TO "userWithWritesToOhdsiSchema";
ALTER DEFAULT PRIVILEGES IN SCHEMA webapi GRANT ALL ON TABLES TO "userWithWritesToOhdsiSchema";

ALTER DEFAULT PRIVILEGES IN SCHEMA cdm GRANT ALL PRIVILEGES ON TABLES TO ohdsi_admin;
ALTER DEFAULT PRIVILEGES IN SCHEMA ohdsi GRANT ALL PRIVILEGES ON TABLES TO ohdsi_admin;
ALTER DEFAULT PRIVILEGES IN SCHEMA ohdsi_results GRANT ALL PRIVILEGES ON TABLES TO ohdsi_admin;
ALTER DEFAULT PRIVILEGES IN SCHEMA webapi GRANT ALL PRIVILEGES ON TABLES TO ohdsi_admin;

ALTER DEFAULT PRIVILEGES IN SCHEMA ohdsi GRANT ALL ON SEQUENCES TO "userWithWritesToOhdsiSchema";
ALTER DEFAULT PRIVILEGES IN SCHEMA ohdsi_results GRANT ALL ON SEQUENCES TO "userWithWritesToOhdsiSchema";
ALTER DEFAULT PRIVILEGES IN SCHEMA webapi GRANT ALL ON SEQUENCES TO "userWithWritesToOhdsiSchema";

ALTER DEFAULT PRIVILEGES IN SCHEMA cdm GRANT ALL PRIVILEGES ON SEQUENCES TO ohdsi_admin;
ALTER DEFAULT PRIVILEGES IN SCHEMA ohdsi GRANT ALL PRIVILEGES ON SEQUENCES TO ohdsi_admin;
ALTER DEFAULT PRIVILEGES IN SCHEMA ohdsi_results GRANT ALL PRIVILEGES ON SEQUENCES TO ohdsi_admin;
ALTER DEFAULT PRIVILEGES IN SCHEMA webapi GRANT ALL PRIVILEGES ON SEQUENCES TO ohdsi_admin;